version: '3'

services:
  moodle:
    build: ./moodle
    ports:
      - "80:80"
    volumes:
      - ./siteroot:/siteroot
  moodle-db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: password
    volumes: 
      - 'moodledb:/var/lib/mysql'
  moodle-test-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'moodletestdb:/var/lib/postgresql'
volumes:
    moodledb:
    moodletestdb:
